# Imagen base 
ARG AIRFLOW_BASE_IMAGE=apache/airflow:2.9.3-python3.11
FROM ${AIRFLOW_BASE_IMAGE}

# Trabajar como usuario 'airflow' (UID 50000)
USER airflow

# Constraints 
ARG AIRFLOW_VERSION=2.9.3
ARG PYTHON_MAJOR_MINOR=3.11
ARG CONSTRAINTS_URL="https://raw.githubusercontent.com/apache/airflow/constraints-${AIRFLOW_VERSION}/constraints-${PYTHON_MAJOR_MINOR}.txt"

# Requerimientos
COPY --chown=airflow:root requirements.txt /requirements.txt
RUN python -m pip install --no-cache-dir --upgrade pip && \
    python -m pip install --no-cache-dir -r /requirements.txt --constraint "${CONSTRAINTS_URL}"